# Generated by Django 2.0 on 2019-12-13 11:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('voting_id',)},
        ),
    ]
