# Generated by Django 2.0 on 2019-12-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_auto_20191213_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='voter_id',
            field=models.TextField(help_text='Introduce users id separated with commas'),
        ),
    ]
