# Generated by Django 2.0 on 2019-12-18 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('census', '0003_auto_20191213_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='census',
            name='voter_id',
        ),
        migrations.AddField(
            model_name='census',
            name='voter_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
