# Generated by Django 2.0 on 2020-01-27 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
        ('census', '0004_auto_20191218_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='census',
            name='voting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Voting'),
        ),
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('name', 'voting_id')},
        ),
    ]
