# Generated by Django 2.0 on 2020-01-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_auto_20200127_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
